name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker Login - Docker Hub
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build e Push no Docker Hub
      run: |
        cd SiteContagem
        docker build . --file Dockerfile --tag aznpregistry/${{ secrets.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER
        docker tag aznpregistry/${{ secrets.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER ${{ secrets.DOCKER_USERNAME }}/${{ secrets.NOME_IMAGEM }}:latest
        docker push aznpregistry/${{ secrets.NOME_IMAGEM }}
        
