name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker Login - Docker Hub
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build e Push no Azure ACR
      run: |
        cd SiteContagem
        docker build . --file Dockerfile --tag ${{ secrets.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER
        docker tag ${{ secrets.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER ${{ secrets.NOME_IMAGEM }}:latest
        docker push ${{ secrets.NOME_IMAGEM }}
        
    - name: Logando no Azure para Deployment
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure WebApp Container - Deployment da Aplicacao
      env:
        WEB_APP: ${{ secrets.WEB_APP }} 
        IMAGEM_DEPLOYMENT: ${{ secrets.NOME_IMAGEM }}:latest
      uses: Azure/webapps-container-deploy@v1
      with:
        app-name: ${{ env.WEB_APP }}
        images: ${{ env.NOME_IMAGEM }}
